### ISSUE TITLE
Question on the update of lambda0 and lambda1

### ISSUE THREAD

**Issue by jcyk** [bastings/interpretable_predictions#1]
Hi, thanks for sharing the code.
Could you please put some explanation on the update of  lambda0 and lambda1 ?
I see that it is updated by the following equations, but do not really follow the idea behind them.
```
self.lambda1 = self.lambda1 * torch.exp(self.lagrange_lr * c1.detach())
self.lambda1 = self.lambda1.clamp(self.lambda_min, self.lambda_max)
```

**Comment by bastings** [comment]
Hi, thanks for your interest!

This line:
```python
self.lambda1 = self.lambda1 * torch.exp(self.lagrange_lr * c1.detach())
```
Updates the lambda term based on (the moving average of) the difference in the current selection rate vs the target selection rate. There are two such rates: one for sparsity (e.g. select 13% of the text, r = 0.13), and one for coherence (e.g. have 2% of transitions, r=0.02).

I basically follow the steps described in Algorithm 1 in this paper (page 7): https://arxiv.org/abs/1810.00597

The clamping restricts the space for lambda (it gives it a min and max value) and it is only really being used for the Beer task, where it makes training slightly more stable.

**Comment by bastings** [comment]
I added some notes about this in the code in commit 410e67e6eba9d5a2411fd64e869eed5429139445 

Let me know if you have any other questions.

**Comment by jcyk** [comment]
Hi, thanks for the reference! 

Another question I would like to ask is that is how is the model's sensitivity to the settngs of `self.lagrange_lr` , `self.lambda_init`, and `self.lagrange_alpha`.

Also, Does the default setting (in the repo) produce the reported results in your paper? 

Thank you very much!

**Comment by bastings** [comment]
Hi, the default settings should give you (approximately) the same results as in the paper (all results are single runs so some variance is expected).

I don't know exactly how sensitive the model is to the lagrange settings, but I have some idea. 
For SST and SNLI it does not seem to matter so much, but I used somewhat more conservative settings there (with a high alpha 0.99, so slower updates to the running average). On Beer data, it seemed useful to update the running average quickly. In all cases it seems beneficial to start with a small initial value for lambda. You would need to experiment further to answer the question fully though.

**Comment by jcyk** [comment]
many thanks to you for your kind reply!
