### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by fsilavong** [bastings/interpretable_predictions#2]
Experiencing this runtime error when I was trying to run the sample code you provided:
```
RuntimeError: "flip_cpu" not implemented for 'Bool'
```
Error was raised when it tries to execute the line `outputs_rev = RCNN._unroll(x.flip(1), self.cell_rev, mask.flip(1))`

**Comment by bastings** [comment]
Hi, it looks like this has something to do with PyTorch 1.2. I'll push a fix in a moment.

**Comment by bastings** [comment]
@fsilavong could you pull the latest code and try again?

**Comment by fsilavong** [comment]
Tried it. It works perfectly 👍 . Thanks!!
